name: Backup Repository

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight (UTC)

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add Backup Repository Remote
        run: |
          git remote add backup https://github.com/MagicDippyEgg/MEMEPEDIA-BACKUP.git
          git fetch backup

      - name: Push to Backup Repository
        run: |
          git push backup main
