name: "Backup Repository"

on:
  push:
    branches: [ main ]
  schedule:
    # Run daily at 00:00 UTC
    - cron: '0 0 * * *'

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Checkout backup repository
        uses: actions/checkout@v4
        with:
          repository: MagicDippyEgg/MEMEPEDIA-BACKUP
          token: ${{ secrets.GH_TOKEN }}
          path: backup

      - name: Copy files to backup directory
        run: |
          # Use rsync to mirror files, excluding Git data and the backup folder itself
          rsync -av --delete --exclude='.git*' --exclude='backup' ./ backup/

      - name: Commit and push changes
        working-directory: backup
        run: |
          # Set commit author to GitHub Actions bot
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Automated backup commit" || echo "No changes to commit"
          git push origin HEAD:main
