name: Backup Repository

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3

    - name: Set up Git configuration
      run: |
        git config --global user.name "MagicDippyEgg"
        git config --global user.email "magicdippyegg@gmail.com"

    - name: Clone backup repository (outside of source)
      run: |
        git clone https://github.com/MagicDippyEgg/MEMEPEDIA-BACKUP.git /tmp/backup_repo

    - name: Copy source files to backup repository
      run: |
        cp -r ./* /tmp/backup_repo/

    - name: Commit and push changes to backup repository
      run: |
        cd /tmp/backup_repo
        git add .
        git commit -m "Automated backup"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/MagicDippyEgg/MEMEPEDIA-BACKUP.git HEAD:main
