name: Backup to GitHub Repository

on:
  push:
    branches:
      - main  # Trigger backup whenever changes are pushed to the main branch (adjust as needed)
  schedule:
    - cron: '0 0 * * *'  # Daily backup at midnight (adjust as needed)

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the main repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Git user
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Clone the backup repository
      - name: Clone backup repository
        run: git clone https://github.com/MagicDippyEgg/MEMEPEDIA-BACKUP.git backup_repo

      # Step 4: Print the directory structure to debug
      - name: List directory contents
        run: |
          echo "Listing files in the current directory:"
          ls -R

      # Step 5: Copy all files from MEMEPEDIA-CONTENT to the backup repository
      - name: Copy files to backup repository
        run: |
          cp -r MEMEPEDIA-CONTENT/* backup_repo/  # Copy all files from MEMEPEDIA-CONTENT folder to backup repo
          
      # Step 6: Commit and push changes
      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the Personal Access Token stored in secrets
        run: |
          cd backup_repo
          git add .
          git commit -m "Backup commit from GitHub Actions"
          git push https://$GH_TOKEN@github.com/MagicDippyEgg/MEMEPEDIA-BACKUP.git
