name: Backup MEMEPEDIA content

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # <--- 🔥 THIS IS THE FIX 🔥

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v4
      with:
        path: source_repo

    - name: Checkout backup repo
      uses: actions/checkout@v4
      with:
        repository: MagicDippyEgg/MEMEPEDIA-BACKUP
        token: ${{ secrets.GITHUB_TOKEN }}
        path: backup_repo

    - name: Clear backup repo
      run: |
        cd backup_repo
        find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +

    - name: Copy files to backup repo
      run: |
        cp -r source_repo/* backup_repo/

    - name: Commit and push backup
      working-directory: backup_repo
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated backup $(date)" || echo "No changes to commit"
        git push
