name: Backup MEMEPEDIA content

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # optional: every day at midnight

jobs:
  backup:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # VERY important so GITHUB_TOKEN can push

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v4

    - name: Clone backup repo
      run: |
        git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/MagicDippyEgg/MEMEPEDIA-BACKUP.git backup_repo

    - name: Copy files
      run: |
        rsync -av --exclude=backup_repo ./ backup_repo/
    
    - name: Commit and push to backup repo
      run: |
        cd backup_repo
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated backup" || echo "Nothing to commit"
        git push origin main
