name: Backup to GitHub

on:
  push:
    branches:
      - main  # Or the branch you want to monitor

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install necessary Python packages
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyGithub

      # Run the backup script
      - name: Run backup script
        run: |
          python backup_to_github.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
