name: Mirror to Codeberg

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch full history for mirroring

      - name: Push to Codeberg
        run: |
          git remote add codeberg https://YourUsername:${{ secrets.CODEBERG_PAT }}@codeberg.org/MagicDippyEgg/MEMEPEDIA.git
          git push --mirror codeberg
