name: Mirror to SourceForge

on:
  push:
    branches:
      - main

jobs:
  push-to-sourceforge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add SourceForge remote
        run: git remote add sourceforge https://git.code.sf.net/p/MEMEPEDIA-CONTENT/git

      - name: Setup Git credentials
        run: |
          echo "https://${{ secrets.SF_USERNAME }}:${{ secrets.SF_PASSWORD }}@git.code.sf.net" > ~/.git-credentials
          git config --global credential.helper 'store --file ~/.git-credentials'

      - name: Push to SourceForge
        run: git push sourceforge main --force
