name: Mirror to SourceForge

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  push-to-sourceforge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add SourceForge remote with credentials
        run: |
          git remote add sourceforge https://${{ secrets.SF_USERNAME }}:${{ secrets.SF_PASSWORD_ENCODED }}@git.code.sf.net/p/MEMEPEDIA-CONTENT/git

      - name: Push to SourceForge
        run: git push sourceforge main --force
