name: Mirror to Bitbucket

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  push-to-bitbucket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # important for full history push

      - name: Push to Bitbucket
        run: |
          git remote add bitbucket https://magicdippyegg:${{ secrets.BB_APP_PASS }}@bitbucket.org/magicdippyegg/MEMEPEDIA-CONTENT.git
          git push bitbucket main --force
