name: Mirror to SourceForge

on:
  push:
    branches:
      - main  # your branch

jobs:
  push-to-sourceforge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # full history for mirroring

      - name: Push to SourceForge
        run: |
          git remote add sourceforge https://${{ secrets.SF_USERNAME }}:${{ secrets.SF_PASSWORD }}@git.code.sf.net/p/MEMEPEDIA-CONTENT/git
          git push sourceforge main --force
